version: '3.8'
services:
  react-native-app:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
